RevenueCat/purchases-capacitor

android/src/main/java/ee/forgr/plugin/capacitor_purchases/CapacitorPurchasesPlugin.java, ios/Plugin/CapacitorPurchasesPlugin.swift, src/definitions.ts
First off, thanks so much for making this plugin!!! A lot of people are finding it really useful. 
I made this PR to address a couple of issues: 
As mentioned in https://github.com/Cap-go/capacitor-purchases/issues/10, on Android observerMode is currently getting set to `true`, which means that all purchases will be cancelled automatically unless the app finishes the transactions by itself. 
I added a parameter to set `observerMode` whenever needed, and also updated the default to `false` for Android, to match the existing value for iOS. 
I also noticed that on Android, the value for `appUserID` was being read and passed along, but it wasn't being read on iOS, so I added that too and updated the typescript definition. 
Lastly I updated to use the latest syntax for configuring the SDK on …
=> Default observerMode on Android to `false`, add option, pass `appUserID` on iOS

README.md, android/src/main/java/com/revenuecat/purchases/capacitor/PurchasesPlugin.kt, example/purchase-tester/src/components/FunctionTesterContainer.tsx, ios/Plugin/PurchasesPlugin.m, ios/Plugin/PurchasesPlugin.swift, src/definitions.ts, src/web.ts
This adds a new method to the plugin: `setMockWebResults`. If you enable it, you will receive some mocked data when using the plugin on the web. Nothing will be affected in the android/ios versions.
=> Add mock responses for web interface

.circleci/config.yml
This fixes the release job in CircleCI. It was failing during `npm publish` because it was trying to build the project but the yarn dependencies were not installed
=> Fix release job in CircleCI

RevenueCatPurchasesCapacitor.podspec, android/build.gradle, fastlane/Fastfile, package.json
We were using single quotes for the podspec file instead of double quotes. That was making the automation to update hybrid common fail. This fixes that and updates to PHC 6.2.0
=> Fix hybrid common upgrades automation

.circleci/config.yml
As part of the `bump` job, we are actually updating the `README.md` with docgen. To do this, we need to install yarn. However, the orb's job isn't actually installing that, so it's failing after creating the PR but before pushing the changes to the VERSIONS.md and the README.md files.
This copies the job from the orb to the repo in order to add an extra step that installs yarn. We could potentially move this to the orb and make it an optional parameter... But since this is only needed here for now, I thought to leave it here. Lmk if you have other thoughts.
=> Fix bump job

ios/Plugin/PurchasesPlugin.swift
This fixes issue #168 where the timestamp parameter wasn't correctly being cast to a String, and was instead resulting in a nil value. Converting first to Int then to String fixes this.
=> Avoid timestamp being cast as nil

ios/Plugin/PurchasesPlugin.swift
This fixes issue #168 where the timestamp parameter wasn't correctly being cast to a String, and was instead resulting in a nil value. Converting first to Int then to String fixes this.
=> [EXTERNAL] Avoid timestamp being cast as nil (#169) via @benmarsh 

ios/Plugin/PluginHelperExtensions.swift
Small update just to remove the "Error x, " prefix on the error.message property returned from the plugin on iOS.
For example, "Error 1, Purchase was cancelled." becomes "Purchase was cancelled."
This matches what the Android version returns.
=> Remove "Error x, " prefix from error messages on iOS

ios/Plugin/PluginHelperExtensions.swift
Contributed by @benmarsh  in #173 
Small update just to remove the "Error x, " prefix on the error.message property returned from the plugin on iOS.
For example, "Error 1, Purchase was cancelled." becomes "Purchase was cancelled."
This matches what the Android version returns.
=> Remove "Error x, " prefix from error messages on iOS (by @benmarsh in #173)

fastlane/Fastfile, ios/Podfile
Tests were running against the latest version of PHC. Instead, we should be using the same version as the version used by the plugin.
=> Fix iOS PHC version when running tests

README.md, android/src/main/java/com/revenuecat/purchases/capacitor/PurchasesPlugin.kt, example/purchase-tester/src/components/FunctionTesterContainer.tsx, ios/Plugin/PurchasesPlugin.m, ios/Plugin/PurchasesPlugin.swift, src/definitions.ts, src/web.ts
Bump to PHC `10.1.0` and add support for new Targeting methods
Get an offering specific to the place of your paywall (eg: onboarding, settings, feature gate, etc). This is determined by Targeting.
```ts
let offering = await Purchases.getCurrentOfferingForPlacement("your-placement-identifier")
if (offering) {
// Navigate to paywall
} else {
// Do nothing or continue to another screen
}
```
A blocking call to sync attributes and fetch new offerings to to be used with Targeting that uses Custom Attributes.
```ts
// Using this result is optional - offerings will be cached for next Purchases.getOfferings() call
let offerings = await Purchases.syncAttributesAndOfferingsIfNeeded()
```
=> Adds`Purchases.getCurrentOfferingForPlacement(placementID)` and `Purchases.syncAttributesAndOfferingsIfNeeded()`

.circleci/config.yml, README.md, example/purchase-tester/src/components/FunctionTesterContainer.tsx, src/definitions.ts, src/web.ts
Seems like there was an issue compiling the purchase tester app after the new APIs were added in #222 (These haven't shipped so it's not a breaking change). I fixed the issue and added building purchase tester to the tests
=> Fix `getCurrentOfferingForPlacement` API issue

.circleci/config.yml
We received an email saying the current version was going to experience brownouts. This moves that to the latest tag.
=> Update CircleCI android machine tag

.circleci/config.yml
Intel machines are deprecated by CircleCI. This updates our machines to use the M1 machines
=> Update to use M1 CircleCI machines

android/src/main/java/com/revenuecat/purchases/capacitor/PurchasesPlugin.kt, ios/Plugin/PropertySetterPluginExtensions.swift
Currently the native processing assumes all attributes will be under a `attributes` parameter in the method call, but that's actually not allowed in the TS interface.
This PR changes the native processing to pick the attributes from the root of the call data, passing the correct parameters to the native side. This is not completely in line with our other methods in the SDK API where we require a specific parameter key, but this solution allows to avoid a breaking change.
=> Fix `setAttributes` method to use parameters in the correct location

README.md, RevenueCatPurchasesCapacitor.podspec, android/build.gradle, android/src/main/java/com/revenuecat/purchases/capacitor/PurchasesPlugin.kt, example/purchase-tester/src/components/FunctionTesterContainer.tsx, ios/Plugin/PropertySetterPluginExtensions.swift, ios/Plugin/PurchasesPlugin.m, ios/Podfile, package.json, src/definitions.ts, src/web.ts
This adds support for the new `setOnesignalUserID` method needed for integration with OneSignal 11+
=> Add support for `setOnesignalUserID` for OneSignal 11+ integration

android/src/main/java/com/revenuecat/purchases/capacitor/PurchasesPlugin.kt
`setProxyURL` should actually be called before calling `configure` in most scenarios.
=> Setting `proxyUrl` should not require SDK to be configured

README.md, src/definitions.ts, src/web.ts
The type definition does not reflect the actual native expectation of the removeCustomerInfoUpdateListener
Thank you for contributing to RevenueCat/purchases-capacitor. Before pressing the "Create Pull Request" button, please provide the following:
<strike>  - [ ] If applicable, unit tests.</strike>
=> Update definitions.ts to reflect true native expectation of the removeCustomerInfoUpdateListener

android/src/main/java/com/revenuecat/purchases/capacitor/PurchasesPlugin.kt, ios/Plugin/PurchasesPlugin.m
This small change will make capacitor to actually resolving or rejecting the promise of syncPurchases. Without this change, syncPurchases function will always return -1 no matter if it is successful or not.
=> Make syncPurchases function to actually returning a promise

android/src/main/java/com/revenuecat/purchases/capacitor/PurchasesPlugin.kt, ios/Plugin/PurchasesPlugin.m
This small change will make capacitor to actually resolving or rejecting the promise of syncPurchases. Without this change, syncPurchases function will always return -1 no matter if it is successful or not.
Contributed by @jarvisluong
=> [EXTERNAL] Make syncPurchases function to actually returning a promise (#305) by @jarvisluong

README.md, src/definitions.ts, src/web.ts
The type definition does not reflect the actual native expectation of the removeCustomerInfoUpdateListener
Contributed by @jarvisluong
=> [EXTERNAL] Update definitions.ts to reflect true native expectation of the removeCustomerInfoUpdateListener (#280) by @jarvisluong

fastlane/Fastfile
`Bump` was broken because it couldn't find phc version https://circleci.com/gh/RevenueCat/purchases-capacitor/2860
=> Fix bump lane

example/purchase-tester/android/app/src/main/AndroidManifest.xml
The default `launchMode` set by Capacitor (`singleTask`) causes issues in the purchase flow if users need to verify the payment in a separate (banking) app. The Google Play overlay is gone when they return to the app, causing the purchase to get canceled. We found and fixed this in a recent [Zendesk ticket](https://revenuecat.zendesk.com/agent/tickets/45929).
I figured it's a good idea for our own sample to give the right _example_. I picked `singleTop`, because that seems closest in behavior to `singleTask`, while still fixing the issue. Let me know what you think!
=> Sets the `launchMode` of the Android sample app to `singleTop`.

android/build.gradle
Compiling the android app in newer android studios was failing because it was trying to use jvm 21, which isn't compatible. Additionally as @JayShortway, we were using a higher version of Java that we should. We were mostly ok, but this brings the levelt to the same as our native android SDK and other hybrids.
=> Downgrade Java version to 1.8 and set kotlin JVM target 1.8 to fix compilation issues in newer android studios

android/src/main/java/com/revenuecat/purchases/capacitor/PurchasesPlugin.kt
We were trying to parse the wrong parameter name in the `removeCustomerInfoUpdateListener` method. This was reported by a customer in zendesk.
=> Fix `removeCustomerInfoUpdateListener` in android

example/purchase-tester/src/App.tsx
~11 days ago, building our sample app started failing with an error like [this](https://app.circleci.com/pipelines/github/RevenueCat/purchases-capacitor/706/workflows/df589a14-49ac-466d-8135-a4db44c601d3/jobs/3667). 
```
yarn install v1.22.22
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
warning eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
warning eslint > @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
warning eslint …
```
=> Remove routing from sample app to fix compile issue

example/purchase-tester/src/components/FunctionTesterContainer.tsx
This PR modifies the purchase tester app to not use purchasesAreCompletedBy=MY_APP by default
=> Run PurchaseTester app with purchasesAreCompletedBy=REVENEUCAT by default

package.json
This PR fixes the repository URL in `package.json` so that uploading the CocoaPods specification works correctly with `pod trunk push`.
=> Fix repo source url for CocoaPods

.circleci/config.yml
There was a problem in the last Capacitor UI release because we were trying to copy the `.npmrc` file to the wrong folder. This fixes that.
=> Fix Capacitor UI SDK release

purchases-capacitor-ui/package.json
The last release didn't correctly include the podspec file, potentially causing issues for users using iOS and our UI package. This fixes that.
=> Fix UI package bundled files reference

purchases-capacitor-ui/src/index.ts
We were not exporting `PAYWALL_RESULT` from the `@revenuecat/purchases-capacitor-ui` library, even though it's part of the API. It was still accessible as part of the `@revenuecat/purchases-capacitor`. However, the API surface for the ui library should be complete. This fixes that.
Note that we still haven't added API tests/api generation to the capacitor library. We should do that but that seems like a separate PR.
=> Export `PAYWALL_RESULT` from UI library

Gemfile.lock
This PR makes bumps [fastlane-plugin-revenuecat_internal](https://github.com/RevenueCat/fastlane-plugin-revenuecat_internal) from `7508f17` to `3f7fffc`. See full diff in <a href="https://github.com/RevenueCat/fastlane-plugin-revenuecat_internal/compare/7508f173ab5224816b52fdfaf8efe5d433c471a1...3f7fffc2e3111e92d2ad86e7c2644743bde69119">compare view</a>.
=> [v10] Update fastlane plugin
